<?php

namespace Database\Seeders;

use App\Models\Campaign;
use App\Models\Donation;
use App\Models\User;
use Illuminate\Database\Seeder;

class DonationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $donatur = User::where('role', 'donatur')->first();
        $campaign = Campaign::where('status', 'approved')->first();

        if (! $donatur || ! $campaign) {
            return;
        }

        Donation::insert([
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER123456789',
                'donor_name' => 'John Doe',
                'anonymous' => false,
                'message' => 'Semoga bermanfaat!',
                'amount' => 50000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER987654321',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 75000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER555555555',
                'donor_name' => 'Jane Smith',
                'anonymous' => false,
                'message' => 'Semoga cepat terkumpul!',
                'amount' => 100000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER111111111',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 25000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER222222222',
                'donor_name' => 'Alice Johnson',
                'anonymous' => false,
                'message' => 'Semoga sukses!',
                'amount' => 150000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER333333333',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 30000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER444444444',
                'donor_name' => 'Bob Williams',
                'anonymous' => false,
                'message' => 'Semoga cepat terkumpul!',
                'amount' => 200000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER666666666',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 5000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER777777777',
                'donor_name' => 'Charlie Brown',
                'anonymous' => false,
                'message' => 'Semoga sukses!',
                'amount' => 120000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER888888888',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 80000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER999999999',
                'donor_name' => 'David Lee',
                'anonymous' => false,
                'message' => 'Semoga cepat terkumpul!',
                'amount' => 90000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER000000000',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 60000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER121212121',
                'donor_name' => 'Eve Adams',
                'anonymous' => false,
                'message' => 'Semoga sukses!',
                'amount' => 110000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER131313131',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 70000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER141414141',
                'donor_name' => 'Frank Miller',
                'anonymous' => false,
                'message' => 'Semoga cepat terkumpul!',
                'amount' => 130000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER151515151',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 40000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER161616161',
                'donor_name' => 'Grace Wilson',
                'anonymous' => false,
                'message' => 'Semoga sukses!',
                'amount' => 140000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER171717171',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 9000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER181818181',
                'donor_name' => 'Henry Davis',
                'anonymous' => false,
                'message' => 'Semoga cepat terkumpul!',
                'amount' => 160000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER191919191',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 20000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER202020202',
                'donor_name' => 'Ivy Martinez',
                'anonymous' => false,
                'message' => 'Semoga sukses!',
                'amount' => 170000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $donatur->id,
                'campaign_id' => $campaign->id,
                'order_id' => 'ORDER212121212',
                'donor_name' => null,
                'anonymous' => true,
                'message' => null,
                'amount' => 30000,
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
